export type Resource = {
  name: string
  type: string
  category: string
  url: string
  rss: string
  description: string
  frequency: string
  slug: string
}

function toSlug(name: string) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
}

const raw: Omit<Resource, 'slug'>[] = [
  { name: "Google AI Blog", type: "Blog", category: "AI Research", url: "https://blog.google/technology/ai/", rss: "https://blog.google/technology/ai/feed/", description: "Official Google AI research and product announcements", frequency: "Weekly" },
  { name: "OpenAI Blog", type: "Blog", category: "AI Research", url: "https://openai.com/blog/", rss: "https://openai.com/blog/feed/", description: "Official OpenAI model releases and safety research", frequency: "Weekly" },
  { name: "Anthropic Research", type: "Blog", category: "AI Research", url: "https://www.anthropic.com/research", rss: "", description: "Claude maker's AI safety and interpretability research", frequency: "Bi-weekly" },
  { name: "DeepMind Blog", type: "Blog", category: "AI Research", url: "https://www.deepmind.com/blog", rss: "", description: "Google DeepMind breakthrough research and projects", frequency: "Monthly" },
  { name: "Meta AI Blog", type: "Blog", category: "AI Research", url: "https://ai.meta.com/blog/", rss: "", description: "Meta AI research, Llama models and open-source AI", frequency: "Weekly" },
  { name: "Hugging Face Blog", type: "Blog", category: "AI Tools", url: "https://huggingface.co/blog", rss: "https://huggingface.co/feed.xml", description: "Open-source AI models, datasets and ML community", frequency: "2-3x weekly" },
  { name: "AI News Aggregator", type: "News", category: "AI News", url: "https://www.artificialintelligence-news.com/", rss: "https://www.artificialintelligence-news.com/feed/", description: "Daily AI industry news and enterprise AI coverage", frequency: "Daily" },
  { name: "Synced", type: "News", category: "AI News", url: "https://syncedreview.com/", rss: "https://syncedreview.com/feed/", description: "AI research summaries and industry news", frequency: "Daily" },
  { name: "The Algorithm MIT", type: "Newsletter", category: "AI News", url: "https://mitsloan.mit.edu/ideas-made-to-matter/algorithm", rss: "", description: "MIT Technology Review's AI and algorithm insights", frequency: "2x weekly" },
  { name: "AI Breakfast", type: "Newsletter", category: "AI News", url: "https://www.morningbrew.com/ai", rss: "", description: "Morning Brew's daily AI industry briefing", frequency: "Daily" },
  { name: "The Rundown AI", type: "Newsletter", category: "AI News", url: "https://www.therundown.ai/", rss: "", description: "Top AI news delivered in 5 minutes each morning", frequency: "Daily" },
  { name: "TLDR AI", type: "Newsletter", category: "AI News", url: "https://tldr.tech/ai", rss: "", description: "Bite-sized AI news, research papers, and tools", frequency: "Daily" },
  { name: "AI Weekly", type: "Newsletter", category: "AI News", url: "https://aiweekly.co/", rss: "https://aiweekly.co/feed.xml", description: "Curated weekly roundup of the best AI content", frequency: "Weekly" },
  { name: "Import AI", type: "Newsletter", category: "AI Research", url: "https://jack-clark.net/", rss: "", description: "Jack Clark's deep dive on AI research and policy", frequency: "Weekly" },
  { name: "The Batch", type: "Newsletter", category: "AI Education", url: "https://www.deeplearning.ai/the-batch/", rss: "", description: "Andrew Ng's weekly AI newsletter from DeepLearning.AI", frequency: "Weekly" },
  { name: "Last Week in AI", type: "Newsletter", category: "AI News", url: "https://lastweekin.ai/", rss: "", description: "Weekly digest of the most important AI papers and news", frequency: "Weekly" },
  { name: "AI Alignment Forum", type: "Community", category: "AI Ethics", url: "https://www.alignmentforum.org/", rss: "", description: "Technical AI safety and alignment research forum", frequency: "Daily" },
  { name: "LessWrong", type: "Community", category: "AI Ethics", url: "https://www.lesswrong.com/", rss: "", description: "Rationality and AI safety community blog", frequency: "Daily" },
  { name: "TechCrunch", type: "News", category: "General Tech", url: "https://techcrunch.com/", rss: "https://techcrunch.com/feed/", description: "Leading tech startup and AI industry news", frequency: "Daily" },
  { name: "The Verge", type: "News", category: "General Tech", url: "https://www.theverge.com/", rss: "https://www.theverge.com/rss/index.xml", description: "Technology, science and culture news", frequency: "Daily" },
  { name: "Ars Technica", type: "News", category: "General Tech", url: "https://arstechnica.com/", rss: "https://feeds.arstechnica.com/arstechnica/index", description: "In-depth technology analysis and reporting", frequency: "Daily" },
  { name: "Wired", type: "News", category: "General Tech", url: "https://www.wired.com/", rss: "https://www.wired.com/feed/rss", description: "Technology, culture and business at the intersection of AI", frequency: "Daily" },
  { name: "VentureBeat", type: "News", category: "AI Business", url: "https://venturebeat.com/", rss: "https://venturebeat.com/feed/", description: "AI enterprise business news and product launches", frequency: "Daily" },
  { name: "Protocol", type: "News", category: "General Tech", url: "https://www.protocol.com/", rss: "https://www.protocol.com/feed", description: "Power, people and policy shaping the tech industry", frequency: "Daily" },
  { name: "Towards Data Science", type: "Blog", category: "Data Science", url: "https://towardsdatascience.com/", rss: "https://towardsdatascience.com/feed", description: "Practical data science, ML tutorials and research", frequency: "Daily" },
  { name: "Machine Learning Mastery", type: "Blog", category: "AI Education", url: "https://machinelearningmastery.com/", rss: "https://machinelearningmastery.com/feed/", description: "Hands-on ML tutorials for practitioners", frequency: "Weekly" },
  { name: "fast.ai", type: "Blog", category: "AI Education", url: "https://www.fast.ai/", rss: "", description: "Practical deep learning for coders — free courses", frequency: "Monthly" },
  { name: "Andrej Karpathy Blog", type: "Blog", category: "AI Research", url: "https://karpathy.github.io/", rss: "", description: "Deep insights on neural networks from former Tesla AI lead", frequency: "Rare" },
  { name: "Distill.pub", type: "Journal", category: "AI Research", url: "https://distill.pub/", rss: "https://distill.pub/journal/feed.xml", description: "Interactive visual explanations of ML research", frequency: "Monthly" },
  { name: "arXiv AI", type: "Research", category: "AI Research", url: "https://arxiv.org/list/cs.AI/recent", rss: "https://arxiv.org/list/cs.AI/rss", description: "Daily preprints in artificial intelligence", frequency: "Daily" },
  { name: "arXiv ML", type: "Research", category: "AI Research", url: "https://arxiv.org/list/cs.LG/recent", rss: "https://arxiv.org/list/cs.LG/rss", description: "Machine learning papers, fresh from researchers", frequency: "Daily" },
  { name: "arXiv NLP", type: "Research", category: "NLP", url: "https://arxiv.org/list/cs.CL/recent", rss: "https://arxiv.org/list/cs.CL/rss", description: "Natural language processing research papers", frequency: "Daily" },
  { name: "arXiv CV", type: "Research", category: "Computer Vision", url: "https://arxiv.org/list/cs.CV/recent", rss: "https://arxiv.org/list/cs.CV/rss", description: "Computer vision and image recognition research", frequency: "Daily" },
  { name: "Papers With Code", type: "Research", category: "AI Research", url: "https://paperswithcode.com/", rss: "", description: "ML papers with open-source code implementations", frequency: "Daily" },
  { name: "Semantic Scholar", type: "Research", category: "AI Research", url: "https://www.semanticscholar.org/", rss: "", description: "Free AI-powered research discovery tool", frequency: "Daily" },
  { name: "Connected Papers", type: "Research", category: "AI Research", url: "https://www.connectedpapers.com/", rss: "", description: "Visual graph of related research papers", frequency: "On-demand" },
  { name: "AI2 Research", type: "Blog", category: "AI Research", url: "https://allenai.org/blog", rss: "", description: "Allen Institute for AI research and open datasets", frequency: "Monthly" },
  { name: "Stanford HAI", type: "Research", category: "AI Policy", url: "https://hai.stanford.edu/news", rss: "", description: "Stanford's human-centered AI research and policy", frequency: "Weekly" },
  { name: "MIT CSAIL", type: "Blog", category: "AI Research", url: "https://www.csail.mit.edu/news", rss: "", description: "MIT computer science and AI lab research updates", frequency: "Weekly" },
  { name: "Future of Life Institute", type: "Blog", category: "AI Ethics", url: "https://futureoflife.org/", rss: "https://futureoflife.org/feed/", description: "AI existential risk research and policy advocacy", frequency: "Weekly" },
  { name: "AI Now Institute", type: "Research", category: "AI Ethics", url: "https://ainowinstitute.org/", rss: "", description: "Social implications of AI and power structures", frequency: "Monthly" },
  { name: "Partnership on AI", type: "Blog", category: "AI Ethics", url: "https://partnershiponai.org/blog/", rss: "", description: "Multi-stakeholder AI governance and best practices", frequency: "Monthly" },
  { name: "Center for AI Safety", type: "Blog", category: "AI Ethics", url: "https://www.safe.ai/blog", rss: "", description: "Technical AI safety research and policy", frequency: "Monthly" },
  { name: "Brookings AI Policy", type: "Blog", category: "AI Policy", url: "https://www.brookings.edu/topic/artificial-intelligence/", rss: "", description: "AI policy analysis from Brookings Institution", frequency: "Weekly" },
  { name: "NIST AI Framework", type: "Blog", category: "AI Policy", url: "https://www.nist.gov/artificial-intelligence", rss: "", description: "National standards for AI risk management", frequency: "Monthly" },
  { name: "EU AI Act Tracker", type: "News", category: "AI Policy", url: "https://artificialintelligenceact.eu/", rss: "", description: "Track EU AI regulation developments in real-time", frequency: "Weekly" },
  { name: "Center for AI and Digital Policy", type: "Blog", category: "AI Policy", url: "https://www.caidp.org/", rss: "", description: "Global AI policy and digital rights advocacy", frequency: "Monthly" },
  { name: "MLOps Community", type: "Community", category: "MLOps", url: "https://mlops.community/", rss: "https://mlops.community/feed/", description: "Practitioners sharing MLOps tools and best practices", frequency: "Weekly" },
  { name: "Kaggle Blog", type: "Blog", category: "Data Science", url: "https://medium.com/kaggle-blog", rss: "", description: "Data science competitions, winners and tutorials", frequency: "Weekly" },
  { name: "Analytics Vidhya", type: "Blog", category: "Data Science", url: "https://www.analyticsvidhya.com/blog/", rss: "", description: "Data science tutorials, competitions, and career tips", frequency: "Daily" },
  { name: "Dev.to AI", type: "Community", category: "Community", url: "https://dev.to/t/ai", rss: "https://dev.to/feed", description: "Developer community posts about AI and ML", frequency: "Daily" },
  { name: "Hacker News AI", type: "Community", category: "Community", url: "https://news.ycombinator.com/?q=AI", rss: "", description: "YC community discussion on AI tools and research", frequency: "Daily" },
  { name: "Reddit r/MachineLearning", type: "Community", category: "Community", url: "https://www.reddit.com/r/MachineLearning/", rss: "", description: "Academic ML discussion and paper sharing", frequency: "Daily" },
  { name: "LinkedIn AI Groups", type: "Community", category: "Community", url: "https://www.linkedin.com/", rss: "", description: "Professional AI networking and thought leadership", frequency: "Daily" },
  { name: "CSS-Tricks", type: "Blog", category: "Education", url: "https://css-tricks.com/", rss: "https://css-tricks.com/feed/", description: "Web development tutorials and design techniques", frequency: "Daily" },
  { name: "Smashing Magazine", type: "Blog", category: "Education", url: "https://www.smashingmagazine.com/", rss: "https://www.smashingmagazine.com/feed/", description: "UX, design, and development best practices", frequency: "Daily" },
  { name: "A List Apart", type: "Blog", category: "Education", url: "https://alistapart.com/", rss: "", description: "Web standards, design and best practices", frequency: "Weekly" },
  { name: "Coursera AI Blog", type: "Blog", category: "Education", url: "https://blog.coursera.org/category/ai-and-machine-learning/", rss: "", description: "AI learning resources and industry trends", frequency: "Weekly" },
  { name: "edX AI Courses", type: "Blog", category: "Education", url: "https://www.edx.org/learn/artificial-intelligence", rss: "", description: "University-level AI courses online", frequency: "Monthly" },
  { name: "DeepLearning.AI", type: "Blog", category: "AI Education", url: "https://www.deeplearning.ai/blog/", rss: "", description: "Andrew Ng's AI courses and learning community", frequency: "Weekly" },
  { name: "Lex Fridman Blog", type: "Blog", category: "AI Education", url: "https://lexfridman.com/blog/", rss: "", description: "AI research interviews, blog posts and podcasts", frequency: "Monthly" },
  { name: "3Blue1Brown", type: "Blog", category: "AI Education", url: "https://www.3blue1brown.com/", rss: "", description: "Visual math and neural network explanations", frequency: "Monthly" },
  { name: "Two Minute Papers", type: "Blog", category: "AI Education", url: "https://www.youtube.com/@TwoMinutePapers", rss: "", description: "Quick breakdowns of the latest AI research papers", frequency: "Weekly" },
  { name: "Yannic Kilcher", type: "Blog", category: "AI Education", url: "https://www.youtube.com/@YannicKilcher", rss: "", description: "Deep dives into ML papers and research trends", frequency: "Weekly" },
  { name: "The Gradient", type: "Blog", category: "AI Education", url: "https://thegradient.pub/", rss: "", description: "In-depth perspectives on AI research and applications", frequency: "Weekly" },
  { name: "AI Trends", type: "News", category: "AI Business", url: "https://www.aitrends.com/", rss: "", description: "Enterprise AI adoption and industry trends", frequency: "Daily" },
  { name: "CB Insights AI", type: "Blog", category: "AI Business", url: "https://www.cbinsights.com/research/artificial-intelligence/", rss: "", description: "AI startup funding, market maps and trends", frequency: "Weekly" },
  { name: "Gartner AI", type: "Blog", category: "AI Business", url: "https://www.gartner.com/en/topics/artificial-intelligence", rss: "", description: "Enterprise AI adoption research and predictions", frequency: "Monthly" },
  { name: "McKinsey AI", type: "Blog", category: "AI Business", url: "https://www.mckinsey.com/capabilities/quantumblack/our-insights", rss: "", description: "AI business strategy and transformation insights", frequency: "Monthly" },
  { name: "Python Weekly", type: "Newsletter", category: "Education", url: "https://www.pythonweekly.com/", rss: "https://www.pythonweekly.com/feed/", description: "Curated Python news, articles and tools", frequency: "Weekly" },
  { name: "Rust Weekly", type: "Newsletter", category: "Education", url: "https://this-week-in-rust.org/", rss: "https://this-week-in-rust.org/rss.xml", description: "The Rust programming language weekly digest", frequency: "Weekly" },
  { name: "KDnuggets", type: "Blog", category: "AI Education", url: "https://www.kdnuggets.com/", rss: "https://www.kdnuggets.com/feed", description: "Data science, ML and AI tutorials and jobs", frequency: "Daily" },
  { name: "EFF Deeplinks", type: "Blog", category: "AI Ethics", url: "https://www.eff.org/deeplinks", rss: "https://www.eff.org/rss/", description: "Digital rights, AI surveillance and privacy advocacy", frequency: "Daily" },
  { name: "Product Hunt", type: "News", category: "AI Products", url: "https://www.producthunt.com/", rss: "https://feeds.producthunt.com/posts/rss", description: "Daily launches of new AI tools and products", frequency: "Daily" },
  { name: "There's an AI For That", type: "Blog", category: "AI Products", url: "https://theresanaiforthat.com/", rss: "", description: "Searchable database of AI tools for every task", frequency: "Daily" },
  { name: "Futurepedia", type: "Blog", category: "AI Products", url: "https://www.futurepedia.io/", rss: "", description: "Largest curated directory of AI tools", frequency: "Daily" },
  { name: "AI Tool Hunt", type: "Blog", category: "AI Products", url: "https://www.aitoolhunt.com/", rss: "", description: "Community-curated AI tools and use cases", frequency: "Daily" },
  { name: "Ben's Bites", type: "Newsletter", category: "AI Products", url: "https://bensbites.com/", rss: "", description: "Daily AI product roundup — what launched, what matters", frequency: "Daily" },
  { name: "Lex Fridman Podcast", type: "Podcast", category: "AI Education", url: "https://lexfridman.com/podcast/", rss: "https://lexfridman.com/feed/podcast/", description: "Long-form conversations with AI and science leaders", frequency: "Weekly" },
  { name: "TWIML AI Podcast", type: "Podcast", category: "AI Education", url: "https://twimlai.com/", rss: "", description: "This Week in ML and AI — interviews with practitioners", frequency: "Weekly" },
  { name: "Practical AI", type: "Podcast", category: "AI Education", url: "https://changelog.com/practicalai", rss: "", description: "Making AI accessible and applicable for practitioners", frequency: "Weekly" },
  { name: "AI in Business", type: "Podcast", category: "AI Business", url: "https://emerj.com/podcast/", rss: "", description: "Applied AI for enterprise leaders and executives", frequency: "Weekly" },
  { name: "Google Scholar Alerts", type: "Research", category: "AI Research", url: "https://scholar.google.com/scholar_alerts", rss: "https://scholar.google.com/scholar_alerts", description: "Personalized academic AI research paper alerts", frequency: "Daily" },
  { name: "AlphaSignal", type: "Newsletter", category: "AI Research", url: "https://alphasignal.ai/", rss: "https://alphasignal.ai/feed", description: "AI research breakthroughs, ranked by impact", frequency: "Daily" },
  { name: "AI Index Stanford", type: "Research", category: "Benchmarks", url: "https://aiindex.stanford.edu/", rss: "", description: "Annual report tracking AI progress and capabilities", frequency: "Annual" },
  { name: "Epoch AI", type: "Research", category: "Benchmarks", url: "https://epochai.org/blog", rss: "", description: "AI compute trends, training runs and scaling analysis", frequency: "Monthly" },
  { name: "HELM Benchmarks", type: "Research", category: "Benchmarks", url: "https://crfm.stanford.edu/helm/", rss: "", description: "Holistic LLM evaluation benchmark from Stanford", frequency: "Quarterly" },
  { name: "Open LLM Leaderboard", type: "Research", category: "Benchmarks", url: "https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard", rss: "", description: "Live ranking of open-source LLM performance", frequency: "Daily" },
  { name: "Andreessen Horowitz AI", type: "Blog", category: "Startups", url: "https://a16z.com/ai/", rss: "", description: "a16z's AI investment thesis, portfolio and trends", frequency: "Weekly" },
  { name: "Y Combinator AI", type: "Blog", category: "Startups", url: "https://www.ycombinator.com/blog", rss: "", description: "YC startup insights and AI company spotlights", frequency: "Weekly" },
  { name: "Sequoia AI", type: "Blog", category: "Startups", url: "https://www.sequoiacap.com/article/ai-powered-generation/", rss: "", description: "Sequoia Capital's AI investment perspectives", frequency: "Monthly" },
  { name: "Crunchbase AI", type: "News", category: "Startups", url: "https://news.crunchbase.com/artificial-intelligence/", rss: "", description: "AI startup funding rounds and valuations", frequency: "Daily" },
  { name: "Thought Leaders in AI", type: "Newsletter", category: "Thought Leaders", url: "https://www.linkedin.com/pulse/topics/artificial-intelligence-s2395/", rss: "", description: "Industry leader perspectives on AI from LinkedIn", frequency: "Daily" },
  { name: "Sam Altman Blog", type: "Blog", category: "Thought Leaders", url: "https://blog.samaltman.com/", rss: "", description: "OpenAI CEO's views on AGI, safety and the future", frequency: "Rare" },
  { name: "Demis Hassabis", type: "Blog", category: "Thought Leaders", url: "https://twitter.com/demishassabis", rss: "", description: "DeepMind CEO updates on AI science and progress", frequency: "Weekly" },
  { name: "Yann LeCun", type: "Blog", category: "Thought Leaders", url: "https://yann.lecun.com/", rss: "", description: "Meta's Chief AI Scientist on deep learning and AGI", frequency: "Monthly" },
  { name: "IEEE Spectrum AI", type: "News", category: "AI Research", url: "https://spectrum.ieee.org/artificial-intelligence", rss: "", description: "Engineering perspectives on AI research and applications", frequency: "Daily" },
  { name: "MIT Technology Review AI", type: "News", category: "Analysis", url: "https://www.technologyreview.com/artificial-intelligence/", rss: "", description: "Authoritative AI analysis from MIT's flagship publication", frequency: "Daily" },
  { name: "New Scientist AI", type: "News", category: "Analysis", url: "https://www.newscientist.com/subject/technology/artificial-intelligence/", rss: "", description: "Scientific perspective on AI developments", frequency: "Daily" },
  { name: "Nature AI", type: "Journal", category: "AI Research", url: "https://www.nature.com/subjects/machine-learning", rss: "", description: "Peer-reviewed ML research in Nature journals", frequency: "Weekly" },
  { name: "Science AI", type: "Journal", category: "AI Research", url: "https://www.science.org/topic/ai-robotics", rss: "", description: "AI breakthroughs published in Science magazine", frequency: "Weekly" },
  { name: "Stratechery", type: "Newsletter", category: "Analysis", url: "https://stratechery.com/", rss: "", description: "Ben Thompson's tech strategy and AI business analysis", frequency: "3x weekly" },
  { name: "Exponential View", type: "Newsletter", category: "Analysis", url: "https://www.exponentialview.co/", rss: "", description: "Azeem Azhar's newsletter on AI and exponential change", frequency: "Weekly" },
  { name: "Import AI Newsletter", type: "Newsletter", category: "Analysis", url: "https://importai.substack.com/", rss: "", description: "Jack Clark's technical AI research briefing", frequency: "Weekly" },
  { name: "AI Snake Oil", type: "Blog", category: "Analysis", url: "https://aisnakeoil.com/", rss: "", description: "Princeton researchers separating AI hype from reality", frequency: "Weekly" },
  { name: "Gary Marcus Blog", type: "Blog", category: "Analysis", url: "https://garymarcus.substack.com/", rss: "", description: "Critical analysis of AI claims and limitations", frequency: "Weekly" },
  { name: "Microsoft Research Blog", type: "Blog", category: "AI Research", url: "https://www.microsoft.com/en-us/research/blog/", rss: "", description: "Microsoft Research AI papers and product launches", frequency: "Weekly" },
  { name: "Amazon Science", type: "Blog", category: "AI Research", url: "https://www.amazon.science/blog", rss: "", description: "Amazon's AI and ML research from Alexa to AWS", frequency: "Weekly" },
  { name: "Apple Machine Learning", type: "Blog", category: "AI Research", url: "https://machinelearning.apple.com/", rss: "", description: "Apple ML research on privacy-preserving AI", frequency: "Monthly" },
  { name: "NVIDIA Research", type: "Blog", category: "AI Research", url: "https://research.nvidia.com/publications", rss: "", description: "GPU and AI infrastructure research from NVIDIA", frequency: "Monthly" },
  { name: "IBM Research AI", type: "Blog", category: "AI Research", url: "https://research.ibm.com/topics/artificial-intelligence", rss: "", description: "IBM's enterprise AI and quantum computing research", frequency: "Monthly" },
  { name: "Open Source AI Weekly", type: "Newsletter", category: "Open Source", url: "https://opensourceai.substack.com/", rss: "", description: "Open-source AI tools, models and community updates", frequency: "Weekly" },
  { name: "EleutherAI Blog", type: "Blog", category: "Open Source", url: "https://blog.eleuther.ai/", rss: "", description: "Open-source large language model research", frequency: "Monthly" },
  { name: "Mistral AI Blog", type: "Blog", category: "Open Source", url: "https://mistral.ai/news/", rss: "", description: "Mistral's open-weight models and European AI news", frequency: "Monthly" },
  { name: "Healthcare AI Weekly", type: "Newsletter", category: "Healthcare AI", url: "https://healthcareai.substack.com/", rss: "", description: "AI in diagnostics, drug discovery and clinical care", frequency: "Weekly" },
  { name: "FinAI Digest", type: "Newsletter", category: "FinTech AI", url: "https://finai.substack.com/", rss: "", description: "AI in fintech, trading, risk and banking", frequency: "Weekly" },
  { name: "SupplyChain AI", type: "Newsletter", category: "Supply Chain AI", url: "https://supplychainai.substack.com/", rss: "", description: "AI for logistics, procurement and supply chain ops", frequency: "Weekly" },
  { name: "AI Education Weekly", type: "Newsletter", category: "Education AI", url: "https://aieducation.substack.com/", rss: "", description: "AI's impact on learning, teaching and edtech", frequency: "Weekly" },
  { name: "Product AI", type: "Newsletter", category: "Product", url: "https://www.productai.club/", rss: "", description: "Product managers building with AI — cases and tools", frequency: "Weekly" },
  { name: "First Round Review AI", type: "Blog", category: "Startups", url: "https://review.firstround.com/", rss: "", description: "Tactical startup building advice including AI adoption", frequency: "Monthly" },
  { name: "The Information AI", type: "News", category: "Analysis", url: "https://www.theinformation.com/technology", rss: "", description: "Premium investigative AI industry journalism", frequency: "Daily" },
  { name: "Platformer", type: "Newsletter", category: "Analysis", url: "https://www.platformer.news/", rss: "", description: "Casey Newton on AI, social media and Big Tech", frequency: "2x weekly" },
  { name: "Diff Newsletter", type: "Newsletter", category: "Analysis", url: "https://diff.substack.com/", rss: "", description: "Byrne Hobart on finance, AI and meta-level trends", frequency: "Weekly" },
  { name: "AI for Robotics", type: "Blog", category: "Robotics", url: "https://robots.ieee.org/", rss: "", description: "Robotics AI research from IEEE", frequency: "Monthly" },
  { name: "Quantum AI Google", type: "Blog", category: "Quantum AI", url: "https://quantumai.google/", rss: "", description: "Google's quantum computing and AI research", frequency: "Monthly" },
  { name: "AI VC Funding", type: "Newsletter", category: "VC", url: "https://vcai.substack.com/", rss: "", description: "Weekly AI startup funding rounds and VC moves", frequency: "Weekly" },
]

export const RESOURCES: Resource[] = raw.map(r => ({ ...r, slug: toSlug(r.name) }))

export const CATEGORIES = [...new Set(RESOURCES.map(r => r.category))].sort()

export const TYPES = [...new Set(RESOURCES.map(r => r.type))].sort()

export const RSS_SOURCES = RESOURCES.filter(r => r.rss && r.rss.length > 0)
